export const description = `
- Loves making [apps](/projects), [artworks](/design) and people smile
- Pescatarian, [cruciverbalist](https://crosshare.org/crosswords/vfN5qIXXAUb6rluYdGPH/break-a-leg) and [ornithophile](https://www.youtube.com/shorts/u-1EousPvG8)
- Excited to work on impactful projects and go the extra mile
- Get in touch at [hello@sciffany.com](mailto:hello@sciffany.com)
`;

export enum ExperienceCategory {
  Software_Engineer = "Software Engineer",
  Data_Engineer = "Data Engineer",
  Teaching_Assistant = "Teaching Assistant",
}

export const experiences = [
  {
    title: "Take App",
    role: "Software Engineer",
    date: "May 2023 - Present",
    link: "https://take.app/",
    description: [
      "Led product decisions with the team",
      "Built core e-commerce features end to end",
      "Integrated multiple payment methods",
      "Launched map-based delivery",
      "Implemented scheduling features",
      "Shipped an analytics dashboard",
    ],
    tech: ["Next.js", "TypeScript"],
    category: ExperienceCategory.Software_Engineer,
  },
  {
    title: "Apple",
    role: "Web Engineer, Reliability Engineering Team",
    date: "July 2020 - August 2020",
    description: ["Built web tools to improve reliability"],
    tech: ["Ember.js", "Ruby on Rails", "PostgreSQL"],
    link: "https://www.apple.com/",
    category: ExperienceCategory.Software_Engineer,
  },
  {
    title: "Runners Planet",
    role: "Software Engineer Intern",
    date: "May 2021 - August 2021",
    description: [
      "Implemented map features for runners",
      "Developed a social network for sports",
    ],
    tech: ["React Native", "GraphQL", "Mapbox", "Getstream"],
    category: ExperienceCategory.Software_Engineer,
  },
  {
    title: "National University of Singapore",
    role: "Student Researcher",
    date: "May 2020 - July 2020",
    description: [
      "Built a visual-novel engine to teach introductory programming",
    ],
    tech: ["Phaser", "React"],
    category: ExperienceCategory.Software_Engineer,
  },
  {
    title: "StaffAny Pte Ltd",
    role: "Fullstack Software Engineer",
    date: "November 2019 - January 2020",
    description: [
      "Developed a web timeclock used by thousands across the country",
    ],
    tech: ["Node.js", "React", "TypeScript"],
    category: ExperienceCategory.Software_Engineer,
  },
  {
    title: "StaffAny Pte Ltd",
    role: "Data Engineering Consultant",
    date: "May 2019 - October 2019",
    description: [
      "Built a BigQuery data warehouse and marts on GCP",
      "Created SQL dashboards for business metrics",
      "Analyzed data with Segment.js library",
      "Informed product decisions with data insights",
    ],
    tech: ["GCP", "BigQuery", "SQL", "Segment.js"],
    category: ExperienceCategory.Data_Engineer,
  },
  {
    title: "Transcelestial Technologies",
    role: "Computer Vision Intern",
    date: "May 2018 - August 2018",
    description: [
      "Wrote a low-latency C++ camera API that raised frame rate from under 100 fps to 2000 fps",
      "Used in a point-and-track laser system for ground-to-satellite communication",
    ],
    tech: ["C++", "Camera API", "Firmware", "Hardware Graphics"],
    category: ExperienceCategory.Software_Engineer,
  },
  {
    title: "Sanfo Intl Trading Inc",
    role: "Computer Programmer",
    date: "August 2017 - February 2019",
    description: [
      "Streamlined inventory and payroll workflows and data",
      "Cut operating time by 16 hours per week",
    ],
    tech: ["Google Apps Script", "FileMaker", "Relational database"],
    category: ExperienceCategory.Software_Engineer,
  },
  {
    title: "Agency for Science and Technology Research",
    role: "Student Researcher",
    date: "June 2015 - February 2016",
    description: ["Researched EEG trends during affective picture viewing"],
    tech: ["MATLAB", "EEG", "Signal processing"],
    category: ExperienceCategory.Software_Engineer,
  },
  {
    title: "National University of Singapore",
    role: "Teaching Assistant",
    date: "August 2018 - December 2018",
    description: [
      "Led tutorials and guided class discussions",
      "Produced teaching materials",
      "Received the Best Tutor Award",
    ],
    tech: ["SICP", "Functional programming"],
    category: ExperienceCategory.Teaching_Assistant,
  },
];

export enum DesignCategory {
  Design = "Design",
  Animation = "Animation",
  Drawings = "Drawings",
  Physical = "Physical",
  All = "All",
}

export const DESIGN_CATEGORIES: readonly DesignCategory[] = [
  DesignCategory.All,
  DesignCategory.Design,
  DesignCategory.Animation,
  DesignCategory.Drawings,
  DesignCategory.Physical,
];

export enum ProjectCategory {
  Utilities = "Utilities",
  SchoolProjects = "School Projects",
  NonTech = "Non-Tech",
}

export const PROJECT_CATEGORIES: readonly ProjectCategory[] = [
  ProjectCategory.Utilities,
  ProjectCategory.SchoolProjects,
  ProjectCategory.NonTech,
];

export const projects = [
  {
    emoji: "🦕",
    title: "Lingosaurus",
    description: "Learn Tagalog and Korean",
    tech: ["Nextjs", "TypeScript"],
    link: "https://lingosaurus.vercel.app/",
    category: ProjectCategory.Utilities,
    image: "/lingosaurus.png",
    slug: "lingosaurus",
    longDescription:
      "Lingosaurus is an incremental and immersive language learning app that allows you to learn Tagalog and Korean.",
    why: "I made this to supplement my Korean language learning and to share Tagalog language with my friends.",
    different:
      "This app generates many sentences for each sentence structure, allowing you to learn through audio repetition. It introduces new vocabulary for each sentence structure.",
  },

  {
    emoji: "🧶",
    title: "Amigurumi Counter",
    description: "Count crochet stitches",
    tech: ["React Native"],
    link: "https://play.google.com/store/apps/details?id=com.sciffany.AmigurumiCounter",
    category: ProjectCategory.Utilities,
    image: "/amigurumi2.png",
    slug: "amigurumi-counter",
  },
  {
    emoji: "🏠",
    title: "Rent Bills",
    description: "Rent management app",
    tech: ["React", "TypeScript"],
    link: "https://github.com/sciffany/rent-bills",
    category: ProjectCategory.Utilities,
    image: "/rent-bills.png",
    slug: "rent-bills",
  },
  {
    emoji: "🔍",
    title: "Static Program Analyser",
    description: "Code parser",
    tech: ["C++"],
    category: ProjectCategory.SchoolProjects,
    slug: "static-program-analyser",
  },
  {
    emoji: "🎤",
    title: "Audio Stenography",
    description: "Conceal messages in audio",
    tech: ["MATLAB"],
    category: ProjectCategory.SchoolProjects,
    slug: "audio-stenography",
  },
  {
    emoji: "🎓",
    title: "PYPagao",
    description: "Crowdsourced exam answers",
    tech: ["Ruby on Rails"],
    link: "https://github.com/turbocharged-potato/pypagao-fullstack",
    category: ProjectCategory.SchoolProjects,
    slug: "pypagao",
  },

  {
    emoji: "🧠",
    title: "Brain research",
    description: "EEG analysis",
    tech: ["MATLAB"],
    link: "https://github.com/sciffany/brain-research",
    category: ProjectCategory.SchoolProjects,
    slug: "brain-research",
  },
  {
    emoji: "🔔",
    title: "NotifBuddy",
    description: "AI assistant scheduler",
    tech: ["Telegram Bot", "Typescript"],
    link: "https://t.me/notifbuddybot",
    category: ProjectCategory.Utilities,
    slug: "notifbuddy",
  },
  {
    emoji: "🔒",
    title: "Masterseal Corporation",
    description: "Security seals website",
    tech: ["Nextjs", "SEO"],
    link: "https://www.mastersealcorporation.com/",
    category: ProjectCategory.NonTech,
    image: "/masterseal.png",
    slug: "masterseal-corporation",
  },
  {
    emoji: "🎤",
    title: "Compositions",
    description: "Music compositions",
    link: "https://musescore.com/user/18234171",
    category: ProjectCategory.NonTech,
    slug: "compositions",
  },
  {
    emoji: "👾",
    title: "Gevardonn",
    description: "Orignal character creations",
    category: ProjectCategory.NonTech,
    slug: "gevardonn",
  },
  {
    emoji: "🎨",
    title: "Redbubble",
    description: "Nerdy t-shirt designs",
    link: "https://www.redbubble.com/people/sciffany/shop",
    category: ProjectCategory.NonTech,
    slug: "redbubble",
  },
  {
    emoji: "🧶",
    title: "Tiff Crochets",
    description: "Crochet artworks",
    link: "https://take.app/tiffcrochets/search",
    category: ProjectCategory.NonTech,
    slug: "tiff-crochets",
  },
];

export enum GameCategory {
  SocialGames = "Social Games",
  Puzzle = "Puzzle",
  RPG = "RPG",
  Powerpet = "Powerpet",
  Flash = "Flash",
  Powerpoint = "Powerpoint",
}

export const games = [
  {
    emoji: "😎",
    title: "samevibes",
    description: "Game of friendly similarities",
    tech: ["Nextjs", "TypeScript"],
    link: "https://samevibes.vercel.app/",
    category: GameCategory.SocialGames,
    image: "/samevibes2.png",
    slug: "samevibes",
  },
  {
    emoji: "🌿",
    title: "Sparky Nature",
    description: "Farming RPG",
    tech: ["Phaser", "React"],
    link: "https://sparkynature.vercel.app/game",
    category: GameCategory.RPG,
    image: "/demo.png",
    slug: "sparky-nature",
  },
  {
    emoji: "🧩",
    title: "Tell Me a Story",
    description: "Puzzle hunt game",
    tech: ["Django"],
    link: "https://sciffany.pythonanywhere.com/puzzle/tell-me-a-story",
    category: GameCategory.Puzzle,
    slug: "tell-me-a-story",
  },
  {
    emoji: "🪐",
    title: "NeatQuiz",
    description: "Nerdy trivia bot",
    tech: ["Telegram Bot", "Typescript"],
    link: "https://t.me/neatquizbot",
    category: GameCategory.Puzzle,
    slug: "neatquiz",
  },
  {
    emoji: "🧊",
    title: "IcyBreaker",
    description: "Icebreaker bot",
    tech: ["Telegram Bot", "Typescript"],
    link: "https://t.me/icybreakerbot",
    category: GameCategory.SocialGames,
    slug: "icybreaker",
  },
  {
    emoji: "🔒",
    title: "Password",
    description: "Password guessing game",
    tech: ["Nextjs"],
    link: "https://pword.vercel.app/",
    category: GameCategory.SocialGames,
    slug: "password",
  },
  {
    emoji: "🔤",
    title: "Passwordle",
    description: "Word guessing game",
    tech: ["Nextjs"],
    link: "https://pword.vercel.app/2",
    category: GameCategory.SocialGames,
    slug: "passwordle",
  },
  {
    emoji: "🔤",
    title: "Entropius Anagram",
    description: "Anagram word game",
    tech: ["Nextjs"],
    link: "/anagram",
    category: GameCategory.Puzzle,
    slug: "entropius-anagram",
  },
  {
    emoji: "🌳",
    title: "Forest Duel",
    description: "Flashcards made fun",
    tech: ["Nextjs"],
    link: "https://forest-duel.vercel.app/",
    category: GameCategory.Puzzle,
    slug: "forest-duel",
  },
  {
    emoji: "🐶",
    title: "Mini Match",
    description: "Match game",
    tech: ["Phaser"],
    link: "/mini-match",
    category: GameCategory.Powerpet,
    slug: "mini-match",
  },
  {
    emoji: "🧱",
    title: "Bubbas' Blocks",
    description: "Block removing game",
    tech: ["Phaser"],
    link: "/bubbas-blocks",
    category: GameCategory.Powerpet,
    slug: "bubbas-blocks",
  },
  {
    emoji: "🎈",
    title: "Mini Bubbles",
    description: "Bubble popping game",
    tech: ["Phaser"],
    link: "/live/mini-bubbles",
    category: GameCategory.Powerpet,
    slug: "mini-bubbles",
  },
  {
    emoji: "🎲",
    title: "Dicey Mice",
    description: "Dice game",
    tech: ["Phaser"],
    link: "/dicey-mice",
    category: GameCategory.Powerpet,
    slug: "dicey-mice",
  },
  {
    emoji: "💣",
    title: "Minesweeper",
    description: "Minesweeper game",
    link: "https://github.com/sciffany/minesweeper",
    category: GameCategory.Puzzle,
    slug: "minesweeper",
  },
  {
    emoji: "🐘",
    title: "Foof Game",
    description: "Adventure game",
    tech: ["Flash", "ActionScript"],
    link: "/foof-game",
    category: GameCategory.Flash,
    slug: "foof-game",
  },
  {
    emoji: "🗺️",
    title: "Map Designer",
    description: "Map editor",
    tech: ["Flash", "ActionScript"],
    link: "/map-designer",
    category: GameCategory.Flash,
    slug: "map-designer",
  },
  {
    emoji: "🏰",
    title: "Tower Defense",
    description: "Tower defense game",
    tech: ["Flash", "ActionScript"],
    link: "/tower-defense",
    category: GameCategory.Flash,
    slug: "tower-defense",
  },
  {
    emoji: "🎄",
    title: "Christmas Game",
    description: "Christmas game",
    link: "/live/christmas",
    category: GameCategory.Powerpoint,
    slug: "christmas",
  },
  {
    emoji: "🐣",
    title: "Happy Egg Maze",
    description: "Maze game",
    link: "/happy-egg-maze",
    category: GameCategory.Powerpoint,
    slug: "happy-egg-maze",
  },
];
